POST http://localhost:8080/products HTTP/1.1
Content-Type: application/json

{
  "name": "My Product 4",
  "price": 140
}

###

GET http://localhost:8080/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzM2OTExOTgsInN1YiI6IjI1YjFlOWZhLTJlODktNDA2ZS04ZWY0LWZiYjVkNzM5ODlhYSJ9.qglghasK65UPKJa0aKStxfRaSTzTc11VVYkmD29E11o
Content-Type: application/json

###
//ba4974f3-515f-4bcb-bde2-955a8283affb

GET http://localhost:8080/products/95a67155-0de2-4f34-a676-3e4dd4509991 HTTP/1.1
Authorization: Bearer djafhgweou
Content-Type: application/json

###

PUT http://localhost:8080/products/95a67155-0de2-4f34-a676-3e4dd4509991 HTTP/1.1
Content-Type: application/json

{
  "name": "My Product Updated",
  "price": 200
}

###

DELETE http://localhost:8080/products/95a67155-0de2-4f34-a676-3e4dd4509991 HTTP/1.1
Content-Type: application/json